
server:
  port: 8080
 
spring:
  datasource:
    username = root
    password = 123456
    url = jdbc:mysql://localhost:3306/wpi?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&autoReconnect=true&jdbcCompliantTruncation=false&serverTimezone=CTT
    driver-class-name = com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 200MB
  thymeleaf:
    prefix:classpath:/templates/
    suffix:.html
    mode:HTML5
    encoding:UTF-8
    content-type:text/html
    cache:false

#showSql
logging:
  level:
     org.example: debug
    

